### ISSUE TITLE
Simplify frontend design

### ISSUE THREAD

**Issue by Huy-Ngo** [Huy-Ngo/acanban#61]
The current design looks good on desktop, but it has some problems too:

- It's not really responsive on mobile yet
- It has colorful gradient background that might be distracting (it seemed to distract our frontend devs too)

In an attempt to make our website as lightweight (a reason we chose web interface is so that it can run on any platform) as possible, we probably should follow [source hut](https://git.sr.ht/~sircmpwn/core.sr.ht/tree) example. Its design is simplistic yet visually pleasing.

**Comment by McSinyx** [comment]
I've been peaking at srht's frontend and my initial impression is that it's way too complicated to study overnight, mostly because there quite many styled elements, none of which is documented.  Rather, I'd suggest using a small and simple (as in easy to use and understand by someone else, e.g. me) CSS framework like [Bulma](https://bulma.io/documentation) (I've no idea how I got it in my bookmarks, but somehow it has just exactly what we need with an intuitive API) (or any other one of your taste).
